export const masteryRankTitles = [
	'Initiate',
	'Silver Initiate',
	'Gold Initiate',
	'Novice',
	'Silver Novice',
	'Gold Novice',
	'Disciple',
	'Silver Disciple',
	'Gold Disciple',
	'Seeker',
	'Silver Seeker',
	'Gold Seeker',
	'Hunter',
	'Silver Hunter',
	'Gold Hunter',
	'Eagle',
	'Silver Eagle',
	'Gold Eagle',
	'Tiger',
	'Silver Tiger',
	'Gold Tiger',
	'Dragon',
	'Silver Dragon',
	'Gold Dragon',
	'Sage',
	'Silver Sage',
	'Gold Sage',
	'Master',
	'Middle Master',
	'True Master',
	'Legendary 1',
	'Legendary 2',
	'Legendary 3',
	'Legendary 4',
	'Legendary 5'
];
